---

- name: Create event task block
  block:
    - name: Create new event
      prompt:
        msg:
          - say: "Event name?"
            ask: name
          - say: "Volume?"
            ask: volume
          - say: "Sponsor?"
            ask: sponsor
          - say: "Contact info?"
            ask: contact
          - say: "Event date (YYYY-MM-DD)?"
            ask: event_date
          - say: "What time does the event start (HH:MM [Finnish time])?"
            ask: event_start_time
          - say: "Event details?"
            ask: details
          - say: "Location?"
            ask: location
          - say: "Maximum number of participants?"
            ask: max_participants
          - say: "Registration opens date (YYYY-MM-DD)?"
            ask: registration_opens
    - name: Capture current timezone offset
      shell: 'TZ=Europe/Helsinki date "+%z"'
      register: tz_offset
    - name: Send HTTP request
      uri:
        url: http://localhost:5000/admin-api/events
        method: POST
        body_format: json
        body:
          name: "{{name}}"
          sponsor: "{{sponsor}}"
          contact: "{{contact}}"
          date: "{{event_date}}T{{event_start_time}}{{tz_offset.stdout}}"
          details: "{{details}}"
          location: "{{location}}"
          maxParticipants: "{{max_participants | int}}"
          registrationOpens: "{{registration_opens}}"
          volume: "{{volume | int}}"
        status_code: 201
      register: result
    - debug:
        msg: "{{ result.json | to_nice_json(indent=2) }}"
  tags:
    - add-event


- name: Get event info task block
  block:
    - name: Get current event
      uri:
        url: http://localhost:5000/admin-api/events/current
        body_format: json
        method: GET
        status_code: 200
      register: result
    - name: Get participants for current event
      uri:
        url: "http://localhost:5000/admin-api/events/{{ result.json.id }}"
        body_format: json
        method: GET
        status_code: 200
      register: result
    - debug:
        msg: "{{ lookup('template', 'event_info.j2') }}"
  tags:
    - get-current-event-info
