---

- name: Install Python 3 Pip
  apt:
    name: python3-pip
    state: latest

- name: Install and configure Ubuntu firewall
  include_tasks: firewall.yml
  tags:
    - firewall

- name: Install Docker CE
  include_role:
    name: haxorof.docker-ce
  vars:
    docker_compose: true
  notify: Ensure docker daemon is running
  tags:
    - docker-ce

- name: Make sure rsync is installed
  apt:
    name: rsync

- include_tasks: certbot.yml
  tags:
    - certbot

- include_tasks: hardening.yml
  tags:
    - hardening
