---
- name: Run npm install & Build the client
  block:
    - name: Run npm install in client directory
      local_action: command bash -c "cd /opt/wds-site-v4 && npm install"
    - name: Build the client (static version)
      local_action: command bash -c "cd /opt/wds-site-v4 && npm run export"
  tags:
    - client

- name: Synchronize client project file to target machine
  become: yes
  synchronize:
    delete: yes
    src: /opt/wds-site-v4/__sapper__/export/
    dest: /opt/wds-site-v4
    archive: yes
    recursive: yes
    rsync_opts:
      - '--exclude=.git'
  tags:
    - client
