---

- name: Install and configure Ubuntu firewall
  include_tasks: firewall.yml
  tags:
    - firewall

- name: Download get-pip.py
  get_url:
      url: 'https://bootstrap.pypa.io/get-pip.py'
      dest: /tmp/get-pip.py


- name: Install pip
  command: "{{ ansible_python_interpreter if ansible_python_interpreter is defined else 'python' }} get-pip.py pip=={{ pip_version }}"
  args:
    chdir: /tmp

- name: Install Docker CE
  include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: true
    docker_package_state: latest
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
  notify: Ensure docker daemon is running
  tags:
    - docker_ce

- name: pip Install docker compose
  pip:
    name: docker-compose
    executable: pip
  tags:
    - docker_ce

- name: pip Install AWS CLI
  pip:
    name: awscli
    executable: pip
  tags:
    - aws

- name: Make sure rsync is installed
  apt:
    name: rsync

- name: set timezone to Europe/Helsinki
  timezone:
    name: Europe/Helsinki

- include_tasks: hardening.yml
  tags:
    - hardening
